(()=>{'use strict';
const EVENT_DAY=Date.UTC(2026,9,19),START=new Date('2026-10-19T20:00:00-03:00').getTime(),END=new Date('2026-10-20T22:00:00-03:00').getTime(),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function remainingDays(date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);const get=t=>Number(parts.find(p=>p.type===t).value);return Math.max(0,Math.round((EVENT_DAY-Date.UTC(get('year'),get('month')-1,get('day')))/86400000));}
function setDigit(selector,value){document.querySelectorAll(selector).forEach(el=>{if(el.textContent!==value){el.textContent=value;el.classList.remove('digit-turn');void el.offsetWidth;el.classList.add('digit-turn');}});}
function tick(){const now=new Date(),days=remainingDays(now),diff=Math.max(0,START-now.getTime()),pad=n=>String(n).padStart(2,'0');setDigit('[data-days]',pad(days));setDigit('[data-hours]',pad(Math.floor(diff/3600000)));setDigit('[data-minutes]',pad(Math.floor(diff/60000)%60));setDigit('[data-seconds]',pad(Math.floor(diff/1000)%60));document.querySelectorAll('.digital-timer').forEach(el=>el.setAttribute('aria-label',days>0?`Faltam ${days} dias. A imersão começa em 19 de outubro às 20h, horário de Brasília.`:now.getTime()<START?'A imersão começa hoje às 20h.':now.getTime()<END?'A imersão já começou.':'Imersão realizada em 19 e 20 de outubro.'));if(now.getTime()>=START){document.querySelectorAll('.timer-word').forEach(el=>el.textContent=now.getTime()<END?'AO VIVO':'REALIZADA');}if(now.getTime()>=END){document.querySelectorAll('a[href*="checkout.expertemtributario.com.br"]').forEach(el=>{el.removeAttribute('href');el.textContent='ESTA TURMA JÁ FOI REALIZADA';el.setAttribute('aria-disabled','true');});}}
tick();setInterval(tick,1000);window.Imersao={remainingDays};
// Equal-width repeated groups keep both moving ribbons continuously filled.
document.querySelectorAll('.ticker-track').forEach(track=>{const first=track.firstElementChild;if(!first)return;const copy=first.cloneNode(true);copy.setAttribute('aria-hidden','true');track.replaceChildren(first,copy);});
const carousel=document.querySelector('.news-carousel');if(carousel){const track=carousel.querySelector('.news-grid'),cards=[...track.children],label=carousel.querySelector('[data-slide-label]'),pause=carousel.querySelector('[data-carousel="pause"]');cards.forEach(card=>{const clone=card.cloneNode(true);clone.setAttribute("aria-hidden","true");clone.setAttribute("tabindex","-1");clone.classList.remove("reveal");track.appendChild(clone);});let current=0,paused=reduced,hovered=false;function show(index){current=(index+cards.length)%cards.length;track.scrollTo({left:cards[current].offsetLeft-cards[0].offsetLeft,behavior:reduced?'instant':'smooth'});label.textContent=`0${current+1} / 0${cards.length}`;}carousel.querySelector('[data-carousel="prev"]').addEventListener('click',()=>show(current-1));carousel.querySelector('[data-carousel="next"]').addEventListener('click',()=>show(current+1));pause.textContent=paused?'Reproduzir':'Pausar';pause.addEventListener('click',()=>{paused=!paused;pause.textContent=paused?'Reproduzir':'Pausar';pause.setAttribute('aria-label',paused?'Ativar avanço automático':'Pausar avanço automático');});carousel.addEventListener('mouseenter',()=>hovered=true);carousel.addEventListener('mouseleave',()=>hovered=false);carousel.addEventListener('touchstart',()=>paused=true,{passive:true});carousel.addEventListener('focusin',()=>hovered=true);carousel.addEventListener('focusout',()=>hovered=false);track.addEventListener('scroll',()=>{const width=cards[0].getBoundingClientRect().width+22;current=Math.min(cards.length-1,Math.round(track.scrollLeft/width));label.textContent=`0${current+1} / 0${cards.length}`;},{passive:true});setInterval(()=>{if(!paused&&!hovered&&!document.hidden)show(current+1);},6500);}
if('IntersectionObserver'in window&&!reduced){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target);}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.documentElement.classList.add('js-motion');}
})();


